STOCK_TICKER = "JPM"
ETF_TICKER = "XLF"
OPTION_TYPE = "Call"
TIME_WINDOW_MINUTES = 15
IV_SOLVER_TOLERANCE = 1e-4
RAW_OPTIONS_TABLE = "options_raw"
CLEAN_OPTIONS_TABLE = "options_cleaned"
ANALYTICS_OPTIONS_TABLE = "options_analytics"
DATABASE_NAME = "database/options.db"
RISK_FREE_RATE = 0.05  # Placeholder for the risk-free rate, can be updated based on current market conditions